language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
install:
  - pip install .
script:
  - python -W default::Warning -m coverage.__main__ run --branch -m pytest --tb short
  - python -m coverage.__main__ report --include 'chatexchange/*'
branches:
  only:
    - master
    - /^travis-ci(\-.+)?$/
env:
  global:
    - secure: "S9c9S/OgKGa7mLz/Ys0aVwbyNtxBubUVWO0i3ew0sm0KwUBFiNNPtWTyCT21jGrjd1Zp0AvMlcSFhJ9auGAMAVIqPTqM1GkNGU5fPwx6Lo3KAGSqW+XN2cAFXljEyAQ2Bhn/ilWeUymC1EpkNRIDarCJZcNsctrs8P3H67gSFtc="
notifications:
  email: false
